### ISSUE TITLE
Error when mounting the plugin

### ISSUE THREAD

**Issue by lorddaren** [gdavison/vault-oracle#3]
I have successfully built the binary and moved it into my plugins directory.
```
[oracle@host1 vault-oracle] $ vault write sys/plugins/catalog/oracle-database-plugin sha_256="18cea3f7c911237fedc6ce571a09283970ab28e6e6732077ac1072d17223244c" command="oracle-database-plugin"
Success! Data written to: sys/plugins/catalog/oracle-database-plugin
[oracle@host1 vault-oracle] $ vault list sys/plugins/catalog/
Keys
----
cassandra-database-plugin
hana-database-plugin
mongodb-database-plugin
mssql-database-plugin
mysql-aurora-database-plugin
mysql-database-plugin
mysql-legacy-database-plugin
mysql-rds-database-plugin
oracle-database-plugin
postgresql-database-plugin

[oracle@host1 vault-oracle] $ vault read sys/plugins/catalog/oracle-database-plugin
Key    	Value
---    	-----
args   	[]
builtin	false
command	/vault/plugins/oracle-database-plugin
name   	oracle-database-plugin
sha256 	GM6j98kRI3/txs5XGgkoOXCrKObmcyB3rBBy0XIjJEw=
```

But when trying to mount the plugin I get this error:
```
vault mount -path=oracle-secrets -plugin-name=oracle-database-plugin -description="Oracle auto generated secrets, not to be manually changed" plugin
Mount error: Error making API request.

URL: POST http://localhost:8200/v1/sys/mounts/oracle-secrets
Code: 400. Errors:

* plugin exited before we could connect
```
I checked the execution permission on the file and everything looks correct and when I try to execute it manually it prints the an appropriate message that it shouldn't be executed outside of vault.

All I have in my vault logs is:
```
2017/08/16 07:49:14.824652 [ERROR] sys: mount failed: path=oracle-secrets/ error=plugin exited before we could connect
```
Any way to debug why it may be exiting early?

**Comment by gdavison** [comment]
I'm away from a computer right now, so can't check it out. What happens when you try running the plugin directly?

**Comment by lorddaren** [comment]
I get this:
```
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

**Comment by gdavison** [comment]
I wonder if it's having a problem loading the Oracle shared libraries. Do you have the libraries in your system library path, as well as where you're building it?
Unfortunately, I'm going to be on vacation and not at a computer until 25 August. If the libraries aren't the problem, I can investigate when I'm back. Also, you could try using a build from https://github.com/hashicorp/vault-plugin-database-oracle (the current repo is moving to the hashicorp repo)

**Comment by lorddaren** [comment]
I followed the newly document oracle plugin on Vaults website and have it working. I did add LD_LIBRARY_PATH and ORACLE_HOME to the vault startup environment so that may have also fixed the issue. Thanks again for the response.
